<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gtk/demo_and_tutorial">
    <file>map.png</file>
    <file compressed="true">interface.ui</file>
    <file compressed="true">person_composite_widget.ui</file>
    <file compressed="true">main_demo.vala</file>
    <file compressed="true">simple_binding/example_alias_and_freeze.vala</file>
    <file compressed="true">simple_binding/example_binder.vala</file>
    <file compressed="true">simple_binding/example_contract_chaining.vala</file>
    <file compressed="true">simple_binding/example_contract_set_data.vala</file>
    <file compressed="true">simple_binding/example_contract_suspension.vala</file>
    <file compressed="true">simple_binding/example_custom_property_binding.vala</file>
    <file compressed="true">simple_binding/example_inspector.vala</file>
    <file compressed="true">simple_binding/example_object_inspector.vala</file>
    <file compressed="true">simple_binding/example_pointer_hold.vala</file>
    <file compressed="true">simple_binding/example_pointer_relay.vala</file>
    <file compressed="true">simple_binding/example_pointer_set_data.vala</file>
    <file compressed="true">simple_binding/example_simple_property_binding.vala</file>
    <file compressed="true">simple_binding/example_state_objects.vala</file>
    <file compressed="true">simple_binding/example_validation.vala</file>
    <file compressed="true">simple_binding/example_value_objects.vala</file>
    <file compressed="true">advanced_binding/example_boolean_conditions.vala</file>
    <file compressed="true">advanced_binding/example_triggers.vala</file>
    <file compressed="true">advanced_binding/example_enum_flags_state.vala</file>
    <file compressed="true">mapping/example_auto_widgets.vala</file>
    <file compressed="true">mapping/example_auto_value_mode_widgets.vala</file>
    <file compressed="true">mapping/example_composite_widgets.vala</file>
    <file compressed="true">mapping/example_auto_container_values.vala</file>
    <file compressed="true">mapping/example_auto_container_mode_values.vala</file>
  </gresource>
</gresources>
