<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gtk/demo_and_tutorial">
    <file>map.png</file>
    <file compressed="true">interface.ui</file>
    <file compressed="true">main_demo.vala</file>
    <file compressed="true">simple_binding/example_alias_and_freeze.vala</file>
    <file compressed="true">simple_binding/example_contract_chaining.vala</file>
    <file compressed="true">simple_binding/example_contract_set_data.vala</file>
    <file compressed="true">simple_binding/example_custom_property_binding.vala</file>
    <file compressed="true">simple_binding/example_inspector.vala</file>
    <file compressed="true">simple_binding/example_pointer_relay.vala</file>
    <file compressed="true">simple_binding/example_pointer_set_data.vala</file>
    <file compressed="true">simple_binding/example_simple_property_binding.vala</file>
    <file compressed="true">simple_binding/example_state_objects.vala</file>
    <file compressed="true">simple_binding/example_validation.vala</file>
    <file compressed="true">simple_binding/example_value_objects.vala</file>
  </gresource>
</gresources>
