<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gtk/g_data_binding_gtk">
    <file compressed="true">data/inspector.ui</file>
    <file compressed="true">data/placeholder.ui</file>
    <file compressed="true">data/pointer_info.ui</file>
    <file>data/chain-link-16.png</file>
    <file>data/chain-relay-16.png</file>
    <file>data/chain-link-24.png</file>
    <file>data/chain-relay-24.png</file>
  </gresource>
</gresources>
