namespace GDataGtk
{
	[Flags]
	public enum EventFilterMode
	{
		SHOW_FULL_DESCRIPTION,
		PROPERTY_NOTIFICATIONS,
		POINTER_SOURCE,
		POINTER_CONNECTION,
		CONTRACT_BINDINGS,
		CONTRACT_CHANGE,
		CONTRACT_EVENTS = CONTRACT_BINDINGS | CONTRACT_CHANGE,
		POINTER_EVENTS = POINTER_SOURCE | POINTER_CONNECTION,
		ALL_SIGNALS = POINTER_EVENTS | CONTRACT_EVENTS,
		ALL = PROPERTY_NOTIFICATIONS | ALL_SIGNALS
	}
}
